### ISSUE TITLE
Doesn't run with elixir 1.1.1

### ISSUE THREAD

**Issue by 0xR** [joshrotenberg/elixir_cowboy_examples#1]
I'm on elixir 1.1.1 and the examples won't run.

Steps to reproduce:
1. git clone
2. cd some example
3. mix deps.get
4. mix run --no-halt

I get this error:

```
== Compilation error on file lib/hello_world/supervisor.ex ==
** (CompileError) lib/hello_world/supervisor.ex:2: module Supervisor.Behaviour is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/hello_world/supervisor.ex:2: HelloWorld.Supervisor (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8


== Compilation error on file lib/hello_world.ex ==
** (CompileError) lib/hello_world.ex:2: module Application.Behaviour is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/hello_world.ex:2: HelloWorld (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by code0100fun** [comment]
For anyone else having this same problem, there is also an excellent example of using Cowboy with Elixir [here](https://github.com/IdahoEv/cowboy-elixir-example/tree/master).

The major modifications are:

``` elixir
# lib/hello_world/supervisor.ex
use Supervisor.Behaviour

# to

use Supervisor
```

and remove `use Application.Behaviour` in `lib/hello_world.ex`

**Comment by joshrotenberg** [comment]
Sorry about this, I haven't been on top of this repo for some time. I'll see if I can spend some time to get it up to date with the latest Elixir and Cowboy versions.
